Docs:Update glossary.adoc
starknet-io/docs-common-content pull request #17
Opened 2024-01-08 07:41 UTC by LevisNgigi

I have added the following terms;
Prover, Sequencer, verifier and node.

2024-01-14 08:27 UTC, stoobie requested changes
Several comments, many are style related.

2024-01-14 08:27 UTC, stoobie commented on modules/ROOT/partials/partial_glossary.adoc
> +A node in the Starknet ecosystem is a computer equipped with Starknet software, contributing significantly to the network's operations. Nodes are vital for the Starknet ecosystem's functionality, sec
```suggestion
A computer, equipped with Starknet software, that contributes significantly to the network's operations. Nodes are vital for the Starknet ecosystem's functionality, security, and overall health. Without nodes, the Starknet network would not be able to function effectively.
```

2024-01-14 08:27 UTC, stoobie commented on modules/ROOT/partials/partial_glossary.adoc
> +A node in the Starknet ecosystem is a computer equipped with Starknet software, contributing significantly to the network's operations. Nodes are vital for the Starknet ecosystem's functionality, sec
It would be great to add a sentence that is more specific about what a node does.

2024-01-14 08:27 UTC, stoobie commented on modules/ROOT/partials/partial_glossary.adoc
> +== Starknet Prover
```suggestion
== prover
```

2024-01-14 08:27 UTC, stoobie commented on modules/ROOT/partials/partial_glossary.adoc
> +Provers serve as the second line of verification in the Starknet network. Their main task is to validate the work of the Sequencers (when they receive the block produced by the Sequencer) and to gene
```suggestion
Provers serve as the second line of verification in the Starknet network. Their main task is to validate the work of the sequencers when they receive the block produced by the sequencer, and to generate proofs that these processes were correctly performed.
```

2024-01-14 08:27 UTC, stoobie commented on modules/ROOT/partials/partial_glossary.adoc
> +== Starknet Sequencer
```suggestion
== sequencer
```

2024-01-14 08:27 UTC, stoobie commented on modules/ROOT/partials/partial_glossary.adoc
> +[#toc-starknet-Sequencer]
```suggestion
[#toc-starknet-sequencer]
```

2024-01-14 08:27 UTC, stoobie commented on modules/ROOT/partials/partial_glossary.adoc
> +Sequencers are the backbone of the Starknet network, akin to Ethereum’s validators. They usher transactions into the system.For networks like Starknet and other platforms utilizing Validity rollups,
```suggestion
Sequencers are the backbone of the Starknet network, akin to Ethereum’s validators. They usher transactions into the system. For networks like Starknet and other platforms utilizing Validity rollups, a similar parallel is drawn. These networks outsource transaction processing to specialized entities and then verify their work. These specialized entities in the context of Validity rollups are known as _sequencers_.
```

2024-01-14 08:27 UTC, stoobie commented on modules/ROOT/partials/partial_glossary.adoc
> +Provers serve as the second line of verification in the Starknet network. Their main task is to validate the work of the Sequencers (when they receive the block produced by the Sequencer) and to gene
Probably should mention something about how a prover is actually proving a Cairo program execution trace.

2024-01-15 19:14 UTC, LevisNgigi commented
Thank you for the review. I have made the necessary changes.

2024-01-24 07:47 UTC, merged