Docs: Add katana installation
starknet-io/docs-common-content pull request #24
Opened 2024-04-10 09:17 UTC by gianalarcon

Hi team

Since I am working on a [katana tutorial](https://github.com/starknet-io/starknet-docs/pull/1191) for starknet-docs.
I suggest to add the katana installation part on this section

Please check @stoobie

2024-04-11 14:15 UTC, stoobie requested changes
A couple of minor suggestions.

I think we should wait to merge this until I finish reviewing the other PR.

2024-04-11 14:15 UTC, stoobie commented on modules/ROOT/partials/partial_environment_setup.adoc
> +. Install dojoup, the installer for the Katana toolchain:
```suggestion
. Install Dojoup, the installer for the Katana toolchain:
```

2024-04-11 14:15 UTC, stoobie commented on modules/ROOT/partials/partial_environment_setup.adoc
> +katana prints the current version.
```suggestion
Katana prints the current version.
```

2024-04-11 14:44 UTC, gianalarcon reviewed
Hi @stoobie. Yes, That's fine, we can wait for the other PR to be reviewed

2024-05-16 14:07 UTC, stoobie requested changes
Other than my comment about the id, we can't mention Katana without also mentioning starknet-devnet-rs.

2024-05-16 14:07 UTC, stoobie commented on modules/ROOT/partials/partial_devtools.adoc
> +[#Katana]
Please leave the id as-is. Id's impact links, so if you change an id, you have to check to make sure that there aren't any existing links to the id that also need to change.

This is not visible, except possibly in URLs, which we in any case want to leave as lower-case.

2024-08-08 06:15 UTC, LandauRaz commented
Added as part of [#1332](https://github.com/starknet-io/starknet-docs/pull/1332). Thanks for all your help, @gianalarcon!

2024-08-08 06:15 UTC, closed without merging